from pydantic import SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    app_env: str = "development"
    release_color: str = "local"
    release_version: str | None = None
    public_base_url: str = "http://localhost:5173"
    frontend_html_path: str = "/frontend/index.html"
    google_site_verification: str | None = None
    naver_site_verification: str | None = None
    cors_allow_origins: str = "http://localhost:5173,http://127.0.0.1:5173"
    cors_allow_origin_regex: str | None = r"^https?://(localhost|127\.0\.0\.1)(:\d+)?$"
    database_url: str = "sqlite:////private/tmp/zerone_online_judge_demo_v5.db"
    database_pool_size: int = 5
    database_max_overflow: int = 5
    database_pool_timeout_seconds: float = 5.0
    redis_url: str | None = None
    scoreboard_cache_ttl_seconds: int = 2
    access_stats_cache_ttl_seconds: int = 5
    access_log_retention_days: int = 365
    audit_log_retention_days: int = 365
    judge_log_retention_days: int = 90
    log_cleanup_batch_size: int = 1000
    enable_demo_seed: bool = False
    allow_empty_otp: bool = False
    bootstrap_service_master_email: str | None = None
    bootstrap_service_master_name: str = "Service Master"
    auth_token_secret: str = "dev-auth-token-secret-change-me"
    auth_token_issuer: str = "zerone-online-judge"
    staff_access_token_ttl_seconds: int = 900
    staff_refresh_token_ttl_seconds: int = 60 * 60 * 24 * 14
    participant_access_token_ttl_seconds: int = 60 * 60 * 6
    otp_ttl_seconds: int = 300
    otp_request_cooldown_seconds: int = 10
    object_storage_backend: str = "local"
    object_storage_endpoint: str = "localhost:9000"
    object_storage_bucket: str = "zerone"
    object_storage_access_key: str = "change-me"
    object_storage_secret_key: str = "change-me"
    object_storage_secure: bool = False
    object_storage_presign_ttl_seconds: int = 900
    local_object_storage_root: str = "/private/tmp/zerone_object_storage"
    openai_api_key: SecretStr | None = None
    openai_model: str = "gpt-5.4"
    verification_ai_enabled: bool = True
    verification_ai_max_input_chars: int = 400_000
    verification_ai_file_max_bytes: int = 64 * 1024
    verification_ai_max_output_tokens: int = 16_000
    verification_ai_timeout_seconds: int = 180
    verification_ai_daily_limit: int = 50
    verification_ai_poll_seconds: float = 3.0
    verification_ai_concurrency: int = 3
    verification_agent_enabled: bool = True
    verification_agent_model: str = "gpt-6-luna"
    verification_agent_max_cost_usd: float = 1.00
    verification_agent_max_input_tokens: int = 300_000
    verification_agent_max_output_tokens: int = 32_000
    verification_agent_max_calls: int = 48
    verification_agent_max_tools: int = 96
    verification_agent_max_runs: int = 16
    verification_agent_max_playground_runs: int = 24
    verification_agent_timeout_seconds: int = 1800
    verification_playground_url: str | None = None
    verification_playground_token: SecretStr | None = None
    smtp_host: str | None = None
    smtp_port: int = 587
    smtp_username: str | None = None
    smtp_password: str | None = None
    smtp_from_email: str | None = None
    smtp_use_tls: bool = True
    smtp_timeout_seconds: int = 20
    mail_delivery_provider: str = "smtp"
    resend_api_key: str | None = None
    resend_from_email: str | None = None
    resend_api_url: str = "https://api.resend.com"
    mail_worker_poll_interval_seconds: float = 2.0
    mail_worker_batch_size: int = 20
    notice_worker_poll_interval_seconds: float = 2.0
    bundle_worker_poll_interval_seconds: float = 1.0
    bundle_worker_batch_size: int = 8
    bundle_worker_max_attempts: int = 5
    package_build_timeout_seconds: float = 3.0
    judge_claim_poll_interval_seconds: float = 0.5
    judge_claim_max_wait_seconds: float = 25.0
    judge_claim_max_batch_size: int = 100
    judge_claim_inline_testcase_max_bytes: int = 2 * 1024 * 1024
    judge_lease_timeout_seconds: int = 120
    judge_node_active_window_seconds: int = 30
    judge_node_prune_after_hours: int = 24
    feature_submission_runtime_metrics: bool = True
    feature_public_scoreboard_penalty: bool = True
    feature_emergency_notice_auto: bool = True
    feature_usage_analytics: bool = True


settings = Settings()
