from pathlib import Path


BACKEND_ROOT = Path(__file__).resolve().parents[2]
ENV_DIR = BACKEND_ROOT / "deploy" / "env"

FILES = {
    "backend.env.example": """APP_ENV=production
PUBLIC_BASE_URL=https://zoj.kr
FRONTEND_HTML_PATH=/frontend/index.html
GOOGLE_SITE_VERIFICATION=
NAVER_SITE_VERIFICATION=
CORS_ALLOW_ORIGINS=https://zoj.kr,https://test.judge.zerone01.kr
CORS_ALLOW_ORIGIN_REGEX=
DATABASE_URL=postgresql+psycopg://zerone:password@postgres:5432/zerone
REDIS_URL=redis://redis:6379/0
DATABASE_POOL_SIZE=5
DATABASE_MAX_OVERFLOW=5
DATABASE_POOL_TIMEOUT_SECONDS=5
SCOREBOARD_CACHE_TTL_SECONDS=2
ACCESS_STATS_CACHE_TTL_SECONDS=5
ACCESS_LOG_RETENTION_DAYS=365
AUDIT_LOG_RETENTION_DAYS=365
JUDGE_LOG_RETENTION_DAYS=90
LOG_CLEANUP_BATCH_SIZE=1000
ENABLE_DEMO_SEED=false
ALLOW_EMPTY_OTP=false
BOOTSTRAP_SERVICE_MASTER_EMAIL=admin@example.com
BOOTSTRAP_SERVICE_MASTER_NAME=Service Master
AUTH_TOKEN_SECRET=change-me-64-byte-random-token-signing-secret
AUTH_TOKEN_ISSUER=zerone-online-judge
OBJECT_STORAGE_BACKEND=minio
OBJECT_STORAGE_ENDPOINT=http://minio:9000
OBJECT_STORAGE_BUCKET=zerone
OBJECT_STORAGE_ACCESS_KEY=zerone-minio
OBJECT_STORAGE_SECRET_KEY=change-me
OBJECT_STORAGE_SECURE=false
OBJECT_STORAGE_PRESIGN_TTL_SECONDS=900
LOCAL_OBJECT_STORAGE_ROOT=/var/lib/zerone-local-objects
STAFF_ACCESS_TOKEN_TTL_SECONDS=900
STAFF_REFRESH_TOKEN_TTL_SECONDS=1209600
PARTICIPANT_ACCESS_TOKEN_TTL_SECONDS=21600
OTP_TTL_SECONDS=300
OTP_REQUEST_COOLDOWN_SECONDS=10
INTERNAL_API_ALLOWED_CIDRS=10.0.0.0/8
MAX_SOURCE_CODE_BYTES=524288
SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_USERNAME=change-me
SMTP_PASSWORD=change-me
SMTP_FROM_EMAIL=no-reply@example.com
SMTP_USE_TLS=true
SMTP_TIMEOUT_SECONDS=20
MAIL_DELIVERY_PROVIDER=smtp
RESEND_API_KEY=
RESEND_FROM_EMAIL=
RESEND_API_URL=https://api.resend.com
MAIL_WORKER_POLL_INTERVAL_SECONDS=2
MAIL_WORKER_BATCH_SIZE=20
BUNDLE_WORKER_POLL_INTERVAL_SECONDS=1
BUNDLE_WORKER_BATCH_SIZE=8
BUNDLE_WORKER_MAX_ATTEMPTS=5
JUDGE_CLAIM_POLL_INTERVAL_SECONDS=0.5
JUDGE_CLAIM_MAX_WAIT_SECONDS=25
JUDGE_CLAIM_MAX_BATCH_SIZE=100
JUDGE_LEASE_TIMEOUT_SECONDS=120

# Persistent operator verification analysis (OpenAI Responses API).
# Set the key only on the server. Empty key disables new AI requests.
OPENAI_API_KEY=
OPENAI_MODEL=gpt-5.4
VERIFICATION_AI_ENABLED=true
VERIFICATION_AI_DAILY_LIMIT=50
VERIFICATION_AI_MAX_INPUT_CHARS=400000
VERIFICATION_AI_FILE_MAX_BYTES=65536
VERIFICATION_AI_MAX_OUTPUT_TOKENS=16000
VERIFICATION_AI_TIMEOUT_SECONDS=180
VERIFICATION_AGENT_ENABLED=true
VERIFICATION_AGENT_MODEL=gpt-5.4-mini
VERIFICATION_AGENT_MAX_COST_USD=0.20
VERIFICATION_AGENT_MAX_INPUT_TOKENS=60000
VERIFICATION_AGENT_MAX_OUTPUT_TOKENS=16000
VERIFICATION_AGENT_MAX_CALLS=10
VERIFICATION_AGENT_MAX_TOOLS=48
VERIFICATION_AGENT_MAX_RUNS=6
VERIFICATION_AGENT_TIMEOUT_SECONDS=900
# Configured by setup-verification-playground.sh on the server.
VERIFICATION_PLAYGROUND_URL=
VERIFICATION_PLAYGROUND_TOKEN=
""",
    "db.env.example": """POSTGRES_DB=zerone
POSTGRES_USER=zerone
POSTGRES_PASSWORD=change-me
""",
    "minio.env.example": """MINIO_ROOT_USER=zerone-minio
MINIO_ROOT_PASSWORD=change-me
""",
}


def main() -> None:
    ENV_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in FILES.items():
        (ENV_DIR / name).write_text(content, encoding="utf-8")
        print(f"generated {ENV_DIR / name}")


if __name__ == "__main__":
    main()
